language: node_js
node_js:
    "8"
sudo: false
notifications:
    email:
        on_success: change
        on_failure: always
env:
  global:
  - secure: P/FM7XOjHRkPGpZ2/Z8hwgUsnXsr/wAIlO8wr5vt9QvV6rGHwQW4P3oGfwsfpCTVAVco6B2AFSVsied88YCbjDMgCal8oCzgbJE3FrDR/jvCyC1XfrTyKUkncxBH5mYgj0q213O757oMg5kWLQ+xd3Vu9WgG+l3YopsZZQXTnTjfPFs5crMH7lD0tBtSb9skwPLOwyTSCNsjwNp7vLzyHoMBNpylbHik4ymqMP/upWJlzYBEAV776YhmgKBeXRe7hAk6c6Gd7cIIqO6Ukrr8jLadd6iE6dC0Dh32h3L+GG3LDnzKqdzJlmH8c0VaUkl0NtXOmlK7srEGaJmPrtE6Ld6eBraGFBjqmrwImsWLqAr9VGSNdcvV2VzFlQcSttl2GRLFG48M7rBf+ArA8d2QeEE/jyggLIq7CDlAg/rUBqrdIWcbI/qsqlJwEXaOCifNrQ2Nnw9rwVPopukh31sPIxLLLlHu+UScq/8i/YKK8bTm4/bdb6UzFm/GEwNFdks4nFdmWjgRlhfj1p2+2m1lBBl5deLE6npVeolVn8VjZSrRy9xuTwDRO6GS8auRrrSaimw79f1c5TcZ514kCbzRSR+1uPT6ERJpMvoq7fqokPaENoRmW2p0NFNXqhSG6Hm08X+e20+UuoQJOfytIshJD62yBlg2uCR5bFw+iPSU8JI=
  - secure: jtQ33riSaucErpze9U2IPs7mBPubdajo0lf5d11EhQx1K7Ewu9iPjsFC8QrtTakqoetpwgn1Ra0DYPDiWGu74C2N6FpkpNUCStmluRV42jYAIgzMjS0rzMHeAiBGLZpxAg2VCfS2npsaBMuFHYhPaIG9N8Xhwlt7yoI2Vf1Je4Cm3kv9BDbqAW1WGv7clNaQLaPhhGu701koZp4NHTemCW3KP4ft7qqhR75YyV9rEvSOfrQIqYr3VMQidPRFolOrmdL1CoKHEFgp51XPKVZWxuWzLDVvlf86JsQFC0v+mzW2qowASEFBjCd+kq4KJfpksTSBbpscg3qOatZRYpJlN3/BbsLaQdO3sT/s9wbOtnH1oob75N22xAZsoLO+blyLEpJbhFU8okC1RTfuXAUv7RLq+me2OQvNdZTUtxbtxOVKUMr5yKGX78KQQ0a4XM6AqPrzLaH8cHjJCEMw0448tFYVHhgET1i5wvenykT/bVy0FzDCvi1fmgbeiPOx6QOweRDPRFqs+L07vXCDDYjW2CkW0AvjgQpCXoL9w6gCStsK4waJe78HkxYCkCx5NhfXHaeNrDjrpqVOAkh9dwqzJFJl6LIPkoGHoFamUzCVupTltIbtY1FvCk71SeWZiln9qMKAmmZwSKRokWtwCCUDZKfLoXSnqeWsDR641zS4xAE=
after_success:
    "curl --ftp-create-dirs -T * -u $FTP_USER:$FTP_PASSWORD ftp://victor.zona.digital/public_shtml/"
